### ISSUE TITLE
Inputs do not work

### ISSUE THREAD

**Issue by gameduo-minsukang** [praneeth527/generate-dbt-docs#6]
Hello. I am currently building a CICD using your GitHub Action.
First of all, I would like to express my gratitude.

I'm using your Github Action like this: 
![image](https://github.com/praneeth527/generate-dbt-docs/assets/131755686/06859764-9d19-4722-822d-321469782dff)

However, there is a problem in the process of passing the input in your code:
![image](https://github.com/praneeth527/generate-dbt-docs/assets/131755686/13b59294-7c33-48e2-87b9-f59683f73a04)

As you can see, the parameters are concatenated without spaces, so the docs are not generated correctly.
I would appreciate it if you could either fix it or suggest an alternative solution.

**Comment by praneeth527** [comment]
Hey @gameduo-minsukang Thanks for raising the issue, I have fixed and released a new tag `v1.3` https://github.com/praneeth527/generate-dbt-docs/releases/tag/v1.3

<img width="876" alt="Screenshot 2024-05-30 at 10 38 02 PM" src="https://github.com/praneeth527/generate-dbt-docs/assets/32166431/b8828463-1c91-4e66-9200-a7b69f36f3b6">
